//This file is generated by CinematicComposor. Do NOT modify!


using UnityEngine;
using System.Collections;


public class TutorialCinematicSequence
{
    public enum TutorialState
    {
        None,
        AirlockCameraZoomIn,
        AirlockCameraReady,
        AirlockWelcome,
        AirlockMouseLookSubtitle,
        AirlockMouseLook,
        AirlockWasdSubtitle,
        AirlockWasdWalk,
        AirlockDoorOpen,
        ArmoryEnter,
        ArmoryPickupMG,
        ShootingRangeGameOver,
        TutorialEnd,
    }

    private TutorialState state;

    public TutorialState State { get { return state; } }

    private ITutorialCinematicSequenceListener listener;

    public TutorialCinematicSequence(ITutorialCinematicSequenceListener l)
    {
        listener = l;
    }

    public IEnumerator StartSequences()
    {
        yield return new WaitForSeconds(1);
        state = TutorialState.AirlockCameraZoomIn;
        if (listener != null) listener.OnAirlockCameraZoomIn();
        while (state != TutorialState.AirlockCameraReady) yield return new WaitForEndOfFrame();
        yield return new WaitForSeconds(1);
        state = TutorialState.AirlockWelcome;
        if (listener != null) listener.OnAirlockWelcome();
        yield return new WaitForSeconds(1);
        state = TutorialState.AirlockMouseLookSubtitle;
        if (listener != null) listener.OnAirlockMouseLookSubtitle();
        while (state != TutorialState.AirlockMouseLook) yield return new WaitForEndOfFrame();
        yield return new WaitForSeconds(3);
        state = TutorialState.AirlockWasdSubtitle;
        if (listener != null) listener.OnAirlockWasdSubtitle();
        while (state != TutorialState.AirlockWasdWalk) yield return new WaitForEndOfFrame();
        yield return new WaitForSeconds(1);
        state = TutorialState.AirlockDoorOpen;
        if (listener != null) listener.OnAirlockDoorOpen();
        while (state != TutorialState.ArmoryEnter) yield return new WaitForEndOfFrame();
        while (state != TutorialState.ArmoryPickupMG) yield return new WaitForEndOfFrame();
        while (state != TutorialState.ShootingRangeGameOver) yield return new WaitForEndOfFrame();
        yield return new WaitForSeconds(2);
        state = TutorialState.TutorialEnd;
        if (listener != null) listener.OnTutorialEnd();
    }
    public void OnAirlockCameraReady() { state = TutorialState.AirlockCameraReady; }
    public void OnAirlockMouseLook() { state = TutorialState.AirlockMouseLook; }
    public void OnAirlockWasdWalk() { state = TutorialState.AirlockWasdWalk; }
    public void OnArmoryEnter() { state = TutorialState.ArmoryEnter; }
    public void OnArmoryPickupMG() { state = TutorialState.ArmoryPickupMG; }
    public void OnShootingRangeGameOver() { state = TutorialState.ShootingRangeGameOver; }
}
public interface ITutorialCinematicSequenceListener
{
    void OnAirlockCameraZoomIn();
    void OnAirlockWelcome();
    void OnAirlockMouseLookSubtitle();
    void OnAirlockWasdSubtitle();
    void OnAirlockDoorOpen();
    void OnTutorialEnd();
}
