/* Notice: This file is generated by fsm.exe. Do not modify! */
using System.Collections.Generic;
public class TutorialFSM
{
    public enum State
    {
        Init = 0,
        AirlockCameraFollow = 1,
        AirlockWelcome = 2,
        AirlockMouseLook = 3,
        AirlockWASDWalk = 4,
        AirlockDoorOpen = 5,
        Tunnel = 6,
        Armory = 7,
        ShootingArea = 8,
        HeadingToFight = 9,
        ArenaField = 10,
        Fini = 11,
    }
    private int cur_state = 0;
    public State CurrentState { get { return (State)cur_state; } }
    private List<ITutorialStateTransitionObserver> observers = new List<ITutorialStateTransitionObserver>();
    public void AddObserver(ITutorialStateTransitionObserver ob)
    {
        if (ob != null && !observers.Contains(ob))
            observers.Add(ob);
    }
    public void RemoveObserver(ITutorialStateTransitionObserver ob)
    {
        if (ob != null && observers.Contains(ob))
            observers.Remove(ob);
    }
    public void OnWaitForSeconds()
    {
        switch (cur_state)
        {
            case 0:
                cur_state = 1;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromInitToAirlockCameraFollowOnWaitForSeconds();
                break;
            case 1:
                cur_state = 2;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromAirlockCameraFollowToAirlockWelcomeOnWaitForSeconds();
                break;
            case 2:
                cur_state = 3;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromAirlockWelcomeToAirlockMouseLookOnWaitForSeconds();
                break;
        }
    }
    public void OnWelcomeAirlock()
    {

    }
    public void OnMouseLookAirlock()
    {
        switch (cur_state)
        {
            case 3:
                cur_state = 4;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromAirlockMouseLookToAirlockWASDWalkOnMouseLookAirlock();
                break;
        }
    }
    public void OnWASDWalkAirlock()
    {
        switch (cur_state)
        {
            case 4:
                cur_state = 5;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromAirlockWASDWalkToAirlockDoorOpenOnWASDWalkAirlock();
                break;
        }
    }
    public void OnEnterArmory()
    {
        switch (cur_state)
        {
            case 5:
                cur_state = 6;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromAirlockDoorOpenToTunnelOnEnterArmory();
                break;
            case 6:
                cur_state = 7;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromTunnelToArmoryOnEnterArmory();
                break;
        }
    }
    public void OnLeaveArmory()
    {
        switch (cur_state)
        {
            case 7:
                cur_state = 9;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromArmoryToHeadingToFightOnLeaveArmory();
                break;
        }
    }
    public void OnEnterPlayground()
    {
        switch (cur_state)
        {
            case 9:
                cur_state = 10;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromHeadingToFightToArenaFieldOnEnterPlayground();
                break;
        }
    }
    public void OnAllBotsKilled()
    {
        switch (cur_state)
        {
            case 10:
                cur_state = 11;
                foreach (var o in observers)
                    if (o != null)
                        o.TransitFromArenaFieldToFiniOnAllBotsKilled();
                break;
        }
    }
}
public interface ITutorialStateTransitionObserver
{
    void TransitFromInitToAirlockCameraFollowOnWaitForSeconds();
    void TransitFromAirlockCameraFollowToAirlockWelcomeOnWaitForSeconds();
    void TransitFromAirlockWelcomeToAirlockMouseLookOnWaitForSeconds();
    void TransitFromAirlockMouseLookToAirlockWASDWalkOnMouseLookAirlock();
    void TransitFromAirlockWASDWalkToAirlockDoorOpenOnWASDWalkAirlock();
    void TransitFromAirlockDoorOpenToTunnelOnEnterArmory();
    void TransitFromTunnelToArmoryOnEnterArmory();
    void TransitFromArmoryToHeadingToFightOnLeaveArmory();
    void TransitFromHeadingToFightToArenaFieldOnEnterPlayground();
    void TransitFromArenaFieldToFiniOnAllBotsKilled();
}
