<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>UberStrike.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UberStrike.Shared\UberStrike.Shared.csproj" />
  </ItemGroup>
</Project>
