using UnityEngine;

/// <summary>
/// Holds lightmap textures for a single map scene.
/// Auto-generated by BeastLightmapConfigBuilder (Tools > Rebuild Beast Lightmap Config).
/// Stored in Assets/Resources/BeastLightmaps/ for runtime loading via Resources.Load.
/// </summary>
[CreateAssetMenu(fileName = "BeastLightmapMapData", menuName = "UberStrike/Beast Lightmap Map Data")]
public class BeastLightmapMapData : ScriptableObject
{
    public Texture2D[] lightmaps;
}
