// <auto-generated>
//   PhotonAotHints.cs — IL2CPP/AOT instantiation hints for Photon dictionary deserialization.
//
//   WHY THIS FILE EXISTS
//   --------------------
//   Photon3Unity3D.dll's Protocol.DeserializeDictionary() reconstructs dictionaries
//   off the wire with runtime generic construction:
//
//       Type t = typeof(Dictionary<,>).MakeGenericType(keyType, valueType);
//       IDictionary d = Activator.CreateInstance(t) as IDictionary;
//       d.Add(key, value);
//
//   keyType / valueType come from Protocol.GetTypeOfCode(byte), whose value-type
//   returns are: int, bool, short, long, byte, float, double (plus reference types,
//   which IL2CPP fully shares and never needs a hint for).
//
//   Under the Mono (JIT) backend MakeGenericType compiles the instantiation on
//   demand. Under IL2CPP (AOT) the fully-constructed Dictionary<K,V> must already
//   exist in the compiled image, or MakeGenericType throws ExecutionEngineException
//   at runtime. IL2CPP only emits a generic instantiation if it is statically
//   referenced somewhere in the linked IL.
//
//   This file statically references every Dictionary<K,V> combination that
//   DeserializeDictionary can construct where at least one of K/V is a value type.
//   The method is never called — IL2CPP code-gens from IL presence, not execution.
//   The [Preserve] attribute keeps the managed linker from stripping it first.
//
//   Reference-type / reference-type combos (e.g. Dictionary<string, object>) are
//   omitted on purpose: IL2CPP shares a single implementation for all reference
//   generic args, so they are always available.
//
//   If Photon3Unity3D.dll is ever updated, re-derive the value-type set from the
//   new GetTypeOfCode and regenerate. See memory/session_2026_05_14_photon_aot_hints.md
// </auto-generated>

using System.Collections;
using System.Collections.Generic;
using UnityEngine.Scripting;

namespace UberStrike.AOT
{
	[Preserve]
	internal static class PhotonAotHints
	{
		/// <summary>
		/// Never invoked. Exists so the IL2CPP compiler emits each Dictionary<K,V>
		/// instantiation that Photon's Protocol.DeserializeDictionary may build at runtime.
		/// </summary>
		[Preserve]
		private static void Touch()
		{
			Use<byte, byte>();
			Use<byte, short>();
			Use<byte, int>();
			Use<byte, long>();
			Use<byte, float>();
			Use<byte, double>();
			Use<byte, bool>();
			Use<short, byte>();
			Use<short, short>();
			Use<short, int>();
			Use<short, long>();
			Use<short, float>();
			Use<short, double>();
			Use<short, bool>();
			Use<int, byte>();
			Use<int, short>();
			Use<int, int>();
			Use<int, long>();
			Use<int, float>();
			Use<int, double>();
			Use<int, bool>();
			Use<long, byte>();
			Use<long, short>();
			Use<long, int>();
			Use<long, long>();
			Use<long, float>();
			Use<long, double>();
			Use<long, bool>();
			Use<float, byte>();
			Use<float, short>();
			Use<float, int>();
			Use<float, long>();
			Use<float, float>();
			Use<float, double>();
			Use<float, bool>();
			Use<double, byte>();
			Use<double, short>();
			Use<double, int>();
			Use<double, long>();
			Use<double, float>();
			Use<double, double>();
			Use<double, bool>();
			Use<bool, byte>();
			Use<bool, short>();
			Use<bool, int>();
			Use<bool, long>();
			Use<bool, float>();
			Use<bool, double>();
			Use<bool, bool>();
			Use<byte, object>();
			Use<short, object>();
			Use<int, object>();
			Use<long, object>();
			Use<float, object>();
			Use<double, object>();
			Use<bool, object>();
			Use<object, byte>();
			Use<object, short>();
			Use<object, int>();
			Use<object, long>();
			Use<object, float>();
			Use<object, double>();
			Use<object, bool>();
		}

		/// <summary>
		/// Exercises the ctor, the IDictionary.Add bridge and the enumerator for
		/// Dictionary&lt;TKey, TValue&gt; — the three members DeserializeDictionary touches.
		/// </summary>
		[Preserve]
		private static void Use<TKey, TValue>()
		{
			var dict = new Dictionary<TKey, TValue>();
			IDictionary boxed = dict;
			boxed.Add(default(TKey), default(TValue));
			foreach (DictionaryEntry entry in boxed)
			{
				_ = entry;
			}
		}
	}
}
