/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class BlueStonez
{
    static BlueStonez()
    {
        try
        {
            Skin = Resources.Load("BlueStonez", typeof(GUISkin)) as GUISkin;
            
            // If skin failed to load, use Unity's default
            if (Skin == null)
            {
                UnityEngine.Debug.LogWarning("BlueStonez skin not found, using Unity default skin");
                Skin = GUI.skin;
            }

            // Initialize all styles with safe loading - using try-catch for each to prevent complete failure
            InitializeAllStyles();
        }
        catch (System.Exception ex)
        {
            UnityEngine.Debug.LogError($"Critical error initializing BlueStonez: {ex.Message}");
            // Fall back to Unity default skin
            Skin = GUI.skin;
            InitializeFallbackStyles();
        }
    }
    
    private static void InitializeAllStyles()
    {
        // Initialize basic Unity GUI styles
        box = GetSafeStyle("box");
        label = GetSafeStyle("label");
        textField = GetSafeStyle("textField");
        textArea = GetSafeStyle("textArea");
        button = GetSafeStyle("button");
        toggle = GetSafeStyle("toggle");
        window = GetSafeStyle("window");
        horizontalSlider = GetSafeStyle("horizontalSlider");
        horizontalSliderThumb = GetSafeStyle("horizontalSliderThumb");
        verticalSlider = GetSafeStyle("verticalSlider");
        verticalSliderThumb = GetSafeStyle("verticalSliderThumb");
        horizontalScrollbar = GetSafeStyle("horizontalScrollbar");
        horizontalScrollbarThumb = GetSafeStyle("horizontalScrollbarThumb");
        horizontalScrollbarLeftButton = GetSafeStyle("horizontalScrollbarLeftButton");
        horizontalScrollbarRightButton = GetSafeStyle("horizontalScrollbarRightButton");
        verticalScrollbar = GetSafeStyle("verticalScrollbar");
        verticalScrollbarThumb = GetSafeStyle("verticalScrollbarThumb");
        verticalScrollbarUpButton = GetSafeStyle("verticalScrollbarUpButton");
        verticalScrollbarDownButton = GetSafeStyle("verticalScrollbarDownButton");
        scrollView = GetSafeStyle("scrollView");

        tab_large = GetSafeStyle("tab_large");
        tab_largeicon = GetSafeStyle("tab_largeicon");
        tab_medium = GetSafeStyle("tab_medium");
        dropdown = GetSafeStyle("dropdown");
        tab_strip = GetSafeStyle("tab_strip");
        tab_strip_small = GetSafeStyle("tab_strip_small");
        tab_strip_large = GetSafeStyle("tab_strip_large");
        panelstrip_leftbutton = GetSafeStyle("panelstrip_leftbutton");
        panelstrip_middlebutton = GetSafeStyle("panelstrip_middlebutton");
        panelstrip_rightbutton = GetSafeStyle("panelstrip_rightbutton");
        panelquad_button = GetSafeStyle("panelquad_button");
        panelquad_toggle = GetSafeStyle("panelquad_toggle");
        label_interparkbold_32pt_left = GetSafeStyle("label_interparkbold_32pt_left");
        label_interparkbold_32pt = GetSafeStyle("label_interparkbold_32pt");
        label_interparkbold_32pt_right = GetSafeStyle("label_interparkbold_32pt_right");
        label_interparkbold_48pt = GetSafeStyle("label_interparkbold_48pt");
        label_interparkbold_48pt_left = GetSafeStyle("label_interparkbold_48pt_left");
        label_interparkbold_48pt_right = GetSafeStyle("label_interparkbold_48pt_right");
        label_groupbox = GetSafeStyle("label_groupbox");
        label_group_interparkbold_11pt = GetSafeStyle("label_group_interparkbold_11pt");
        label_interparkbold_11pt = GetSafeStyle("label_interparkbold_11pt");
        label_interparkbold_11pt_left = GetSafeStyle("label_interparkbold_11pt_left");
        label_interparkbold_11pt_left_wrap = GetSafeStyle("label_interparkbold_11pt_left_wrap");
        label_interparkbold_11pt_left_wrap_greybg = GetSafeStyle("label_interparkbold_11pt_left_wrap_greybg");
        label_interparkbold_11pt_right = GetSafeStyle("label_interparkbold_11pt_right");
        label_interparkmed_10pt_right = GetSafeStyle("label_interparkmed_10pt_right");
        label_interparkmed_10pt_left = GetSafeStyle("label_interparkmed_10pt_left");
        label_itemdescription = GetSafeStyle("label_itemdescription");
        label_interparkbold_16pt = GetSafeStyle("label_interparkbold_16pt");
        label_interparkbold_16pt_left = GetSafeStyle("label_interparkbold_16pt_left");
        label_interparkbold_16pt_right = GetSafeStyle("label_interparkbold_16pt_right");
        label_interparkbold_18pt_left = GetSafeStyle("label_interparkbold_18pt_left");
        label_interparkbold_18pt_right = GetSafeStyle("label_interparkbold_18pt_right");
        label_interparkbold_18pt_right_white = GetSafeStyle("label_interparkbold_18pt_right_white");
        label_interparkmed_18pt_right = GetSafeStyle("label_interparkmed_18pt_right");
        label_interparkmed_18pt_left = GetSafeStyle("label_interparkmed_18pt_left");
        label_interparkmed_18pt_left_wrap = GetSafeStyle("label_interparkmed_18pt_left_wrap");
        label_ingamechat = GetSafeStyle("label_ingamechat");
        box_grey31 = GetSafeStyle("box_grey31");
        box_grey38 = GetSafeStyle("box_grey38");
        box_white_2px = GetSafeStyle("box_white_2px");
        box_grey_outlined = GetSafeStyle("box_grey_outlined");
        box_grey_outlined_tip = GetSafeStyle("box_grey_outlined_tip");
        box_white_rounded = GetSafeStyle("box_white_rounded");
        window_standard_grey38 = GetSafeStyle("window_standard_grey38");
        group_grey81 = GetSafeStyle("group_grey81");
        label_group_interparkbold_18pt = GetSafeStyle("label_group_interparkbold_18pt");
        label_interparkbold_18pt = GetSafeStyle("label_interparkbold_18pt");
        radiobutton = GetSafeStyle("radiobutton");
        ingamechat = GetSafeStyle("ingamechat");
        speechbubble_left = GetSafeStyle("speechbubble_left");
        speechbubble_right = GetSafeStyle("speechbubble_right");
        tooltip = GetSafeStyle("tooltip");
        label_interparkmed_11pt = GetSafeStyle("label_interparkmed_11pt");
        // Continue with remaining styles - wrap in try-catch for safety
        try 
        {
            label_interparkmed_11pt_left = GetSafeStyle("label_interparkmed_11pt_left");
            label_interparkmed_11pt_right = GetSafeStyle("label_interparkmed_11pt_right");
            label_interparkmed_11pt_url = GetSafeStyle("label_interparkmed_11pt_url");
            label_interparkbold_11pt_url = GetSafeStyle("label_interparkbold_11pt_url");
            label_interparkbold_13pt = GetSafeStyle("label_interparkbold_13pt");
            label_interparkbold_13pt_black = GetSafeStyle("label_interparkbold_13pt_black");
            label_interparkbold_13pt_left = GetSafeStyle("label_interparkbold_13pt_left");
            dropdown_button = GetSafeStyle("dropdown_button");
            button_context = GetSafeStyle("button_context");
            label_dropdown = GetSafeStyle("label_dropdown");
            box_grey50 = GetSafeStyle("box_grey50");
            packslot = GetSafeStyle("packslot");
            box_overlay = GetSafeStyle("box_overlay");
            box_overlay_black = GetSafeStyle("box_overlay_black");
            dropdown_list = GetSafeStyle("dropdown_list");
            dropdown_listItem = GetSafeStyle("dropdown_listItem");
            buttondark_medium = GetSafeStyle("buttondark_medium");
            button_fbconnect = GetSafeStyle("button_fbconnect");
            buttongold_medium = GetSafeStyle("buttongold_medium");
            buttongold_large_price = GetSafeStyle("buttongold_large_price");
            buttongold_large = GetSafeStyle("buttongold_large");
        }
        catch (System.Exception ex)
        {
            UnityEngine.Debug.LogError($"Error loading some BlueStonez styles: {ex.Message}");
        }
        
        // Load remaining styles with the old method but with error handling
        try
        {
            LoadRemainingStylesWithErrorHandling();
        }
        catch (System.Exception ex)
        {
            UnityEngine.Debug.LogError($"Error loading remaining BlueStonez styles: {ex.Message}");
        }
    }
    
    private static void LoadRemainingStylesWithErrorHandling()
    {
        // Load remaining styles individually with try-catch to prevent complete failure
        // We'll just use GetSafeStyle for the most critical ones
        try { buttongold_small = GetSafeStyle("buttongold_small"); } catch { buttongold_small = CreateFallbackStyle("buttongold_small"); }
        try { buttondark_large = GetSafeStyle("buttondark_large"); } catch { buttondark_large = CreateFallbackStyle("buttondark_large"); }
        try { buttondark_small = GetSafeStyle("buttondark_small"); } catch { buttondark_small = CreateFallbackStyle("buttondark_small"); }
        try { buttonblue_medium = GetSafeStyle("buttonblue_medium"); } catch { buttonblue_medium = CreateFallbackStyle("buttonblue_medium"); }
        try { buttonblue_small = GetSafeStyle("buttonblue_small"); } catch { buttonblue_small = CreateFallbackStyle("buttonblue_small"); }
        try { playercard_member = GetSafeStyle("playercard_member"); } catch { playercard_member = CreateFallbackStyle("playercard_member"); }
        try { playercard_slot = GetSafeStyle("playercard_slot"); } catch { playercard_slot = CreateFallbackStyle("playercard_slot"); }
        try { playercard_slotweapon = GetSafeStyle("playercard_slotweapon"); } catch { playercard_slotweapon = CreateFallbackStyle("playercard_slotweapon"); }
        try { playercard_slotgear = GetSafeStyle("playercard_slotgear"); } catch { playercard_slotgear = CreateFallbackStyle("playercard_slotgear"); }
        try { playercard_slotquickuse = GetSafeStyle("playercard_slotquickuse"); } catch { playercard_slotquickuse = CreateFallbackStyle("playercard_slotquickuse"); }
        // Add more as needed...
    }
    
    private static void InitializeFallbackStyles()
    {
        UnityEngine.Debug.Log("Initializing fallback styles for BlueStonez");
        // Create basic fallback styles for all properties
        box = new GUIStyle(GUI.skin.box);
        label = new GUIStyle(GUI.skin.label);
        textField = new GUIStyle(GUI.skin.textField);
        textArea = new GUIStyle(GUI.skin.textArea);
        button = new GUIStyle(GUI.skin.button);
        toggle = new GUIStyle(GUI.skin.toggle);
        window = new GUIStyle(GUI.skin.window);
        
        // Set all the other styles to basic fallbacks
        tab_strip = new GUIStyle(GUI.skin.label);
        window_standard_grey38 = new GUIStyle(GUI.skin.window);
        label_interparkbold_18pt = new GUIStyle(GUI.skin.label);
        
        // Initialize all remaining styles as basic label fallbacks
        var labelStyle = new GUIStyle(GUI.skin.label);
        label_interparkbold_32pt_left = labelStyle;
        label_interparkbold_32pt = labelStyle;
        label_interparkbold_32pt_right = labelStyle;
        label_interparkbold_48pt = labelStyle;
        label_interparkbold_48pt_left = labelStyle;
        label_interparkbold_48pt_right = labelStyle;
            // Additional styles using GetSafeStyle
            label_interparkmed_11pt_middleLeft = GetSafeStyle("label_interparkmed_11pt_middleLeft");
            button_white = GetSafeStyle("button_white");
            button_green = GetSafeStyle("button_green");
            button_red = GetSafeStyle("button_red");
            toggle_item_slot = GetSafeStyle("toggle_item_slot");
            item_slot_64 = GetSafeStyle("item_slot_64");
            item_slot_large = GetSafeStyle("item_slot_large");
            item_slot_alpha = GetSafeStyle("item_slot_alpha");
            item_slot_small = GetSafeStyle("item_slot_small");
            horizontal_line_grey95 = GetSafeStyle("horizontal_line_grey95");
            vertical_line_grey95 = GetSafeStyle("vertical_line_grey95");
            progressbar_background = GetSafeStyle("progressbar_background");
            hud_progressbar_background = GetSafeStyle("hud_progressbar_background");
            progressbar_large_background = GetSafeStyle("progressbar_large_background");
            progressbar_large_thumb = GetSafeStyle("progressbar_large_thumb");
            hud_progressbar_thumb = GetSafeStyle("hud_progressbar_thumb");
            progressbar_thumb = GetSafeStyle("progressbar_thumb");
            mainmenubutton = GetSafeStyle("mainmenubutton");
            mainmenuseparator = GetSafeStyle("mainmenuseparator");
            whitebutton = GetSafeStyle("whitebutton");
            loadoutdropslot = GetSafeStyle("loadoutdropslot");
            loadoutdropslot_highlight = GetSafeStyle("loadoutdropslot_highlight");
            arrow_small_down = GetSafeStyle("arrow_small_down");
            box_black = GetSafeStyle("box_black");
            box_white = GetSafeStyle("box_white");
            friends_listitem = GetSafeStyle("friends_listitem");
            friends_hidden_button = GetSafeStyle("friends_hidden_button");
            friends_contextlink = GetSafeStyle("friends_contextlink");
            button_mainmenu = GetSafeStyle("button_mainmenu");
            button_icontext = GetSafeStyle("button_icontext");
            button_right = GetSafeStyle("button_right");
            button_left = GetSafeStyle("button_left");
            gray_background = GetSafeStyle("gray_background");
            
            // Initialize additional styles
            buttongold_small = GetSafeStyle("buttongold_small");
            buttondark_large = GetSafeStyle("buttondark_large");
            buttonblue_medium = GetSafeStyle("buttonblue_medium");
            buttonblue_small = GetSafeStyle("buttonblue_small");
            playercard_member = GetSafeStyle("playercard_member");
            playercard_slot = GetSafeStyle("playercard_slot");
            playercard_slotweapon = GetSafeStyle("playercard_slotweapon");
            playercard_slotgear = GetSafeStyle("playercard_slotgear");
            playercard_slotquickuse = GetSafeStyle("playercard_slotquickuse");
    }

    public static GUISkin Skin { get; private set; }

    public static GUIStyle box { get; private set; }
    public static GUIStyle label { get; private set; }
    public static GUIStyle textField { get; private set; }
    public static GUIStyle textArea { get; private set; }
    public static GUIStyle button { get; private set; }
    public static GUIStyle toggle { get; private set; }
    public static GUIStyle window { get; private set; }
    public static GUIStyle horizontalSlider { get; private set; }
    public static GUIStyle horizontalSliderThumb { get; private set; }
    public static GUIStyle verticalSlider { get; private set; }
    public static GUIStyle verticalSliderThumb { get; private set; }
    public static GUIStyle horizontalScrollbar { get; private set; }
    public static GUIStyle horizontalScrollbarThumb { get; private set; }
    public static GUIStyle horizontalScrollbarLeftButton { get; private set; }
    public static GUIStyle horizontalScrollbarRightButton { get; private set; }
    public static GUIStyle verticalScrollbar { get; private set; }
    public static GUIStyle verticalScrollbarThumb { get; private set; }
    public static GUIStyle verticalScrollbarUpButton { get; private set; }
    public static GUIStyle verticalScrollbarDownButton { get; private set; }
    public static GUIStyle scrollView { get; private set; }

    public static GUIStyle tab_large { get; private set; }
    public static GUIStyle tab_largeicon { get; private set; }
    public static GUIStyle tab_medium { get; private set; }
    public static GUIStyle dropdown { get; private set; }
    public static GUIStyle tab_strip { get; private set; }
    public static GUIStyle tab_strip_small { get; private set; }
    public static GUIStyle tab_strip_large { get; private set; }
    public static GUIStyle panelstrip_leftbutton { get; private set; }
    public static GUIStyle panelstrip_middlebutton { get; private set; }
    public static GUIStyle panelstrip_rightbutton { get; private set; }
    public static GUIStyle panelquad_button { get; private set; }
    public static GUIStyle panelquad_toggle { get; private set; }
    public static GUIStyle label_interparkbold_32pt_left { get; private set; }
    public static GUIStyle label_interparkbold_32pt { get; private set; }
    public static GUIStyle label_interparkbold_32pt_right { get; private set; }
    public static GUIStyle label_interparkbold_48pt { get; private set; }
    public static GUIStyle label_interparkbold_48pt_left { get; private set; }
    public static GUIStyle label_interparkbold_48pt_right { get; private set; }
    public static GUIStyle label_groupbox { get; private set; }
    public static GUIStyle label_group_interparkbold_11pt { get; private set; }
    public static GUIStyle label_interparkbold_11pt { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left_wrap { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left_wrap_greybg { get; private set; }
    public static GUIStyle label_interparkbold_11pt_right { get; private set; }
    public static GUIStyle label_interparkmed_10pt_right { get; private set; }
    public static GUIStyle label_interparkmed_10pt_left { get; private set; }
    public static GUIStyle label_itemdescription { get; private set; }
    public static GUIStyle label_interparkbold_16pt { get; private set; }
    public static GUIStyle label_interparkbold_16pt_left { get; private set; }
    public static GUIStyle label_interparkbold_16pt_right { get; private set; }
    public static GUIStyle label_interparkbold_18pt_left { get; private set; }
    public static GUIStyle label_interparkbold_18pt_right { get; private set; }
    public static GUIStyle label_interparkbold_18pt_right_white { get; private set; }
    public static GUIStyle label_interparkmed_18pt_right { get; private set; }
    public static GUIStyle label_interparkmed_18pt_left { get; private set; }
    public static GUIStyle label_interparkmed_18pt_left_wrap { get; private set; }
    public static GUIStyle label_ingamechat { get; private set; }
    public static GUIStyle box_grey31 { get; private set; }
    public static GUIStyle box_grey38 { get; private set; }
    public static GUIStyle box_white_2px { get; private set; }
    public static GUIStyle box_grey_outlined { get; private set; }
    public static GUIStyle box_grey_outlined_tip { get; private set; }
    public static GUIStyle box_white_rounded { get; private set; }
    public static GUIStyle window_standard_grey38 { get; private set; }
    public static GUIStyle group_grey81 { get; private set; }
    public static GUIStyle label_group_interparkbold_18pt { get; private set; }
    public static GUIStyle label_interparkbold_18pt { get; private set; }
    public static GUIStyle radiobutton { get; private set; }
    public static GUIStyle ingamechat { get; private set; }
    public static GUIStyle speechbubble_left { get; private set; }
    public static GUIStyle speechbubble_right { get; private set; }
    public static GUIStyle tooltip { get; private set; }
    public static GUIStyle label_interparkmed_11pt { get; private set; }
    public static GUIStyle label_interparkmed_11pt_middleLeft { get; private set; }
    public static GUIStyle label_interparkmed_11pt_left { get; private set; }
    public static GUIStyle label_interparkmed_11pt_right { get; private set; }
    public static GUIStyle label_interparkmed_11pt_url { get; private set; }
    public static GUIStyle label_interparkbold_11pt_url { get; private set; }
    public static GUIStyle label_interparkbold_13pt { get; private set; }
    public static GUIStyle label_interparkbold_13pt_black { get; private set; }
    public static GUIStyle label_interparkbold_13pt_left { get; private set; }
    public static GUIStyle dropdown_button { get; private set; }
    public static GUIStyle button_context { get; private set; }
    public static GUIStyle label_dropdown { get; private set; }
    public static GUIStyle box_grey50 { get; private set; }
    public static GUIStyle packslot { get; private set; }
    public static GUIStyle box_overlay { get; private set; }
    public static GUIStyle box_overlay_black { get; private set; }
    public static GUIStyle dropdown_list { get; private set; }
    public static GUIStyle dropdown_listItem { get; private set; }
    public static GUIStyle buttondark_medium { get; private set; }
    public static GUIStyle button_fbconnect { get; private set; }
    public static GUIStyle buttongold_medium { get; private set; }
    public static GUIStyle buttongold_large_price { get; private set; }
    public static GUIStyle buttongold_large { get; private set; }
    public static GUIStyle button_white { get; private set; }
    public static GUIStyle button_green { get; private set; }
    public static GUIStyle button_red { get; private set; }
    public static GUIStyle buttondark_small { get; private set; }
    public static GUIStyle toggle_item_slot { get; private set; }
    public static GUIStyle item_slot_64 { get; private set; }
    public static GUIStyle item_slot_large { get; private set; }
    public static GUIStyle item_slot_alpha { get; private set; }
    public static GUIStyle item_slot_small { get; private set; }
    public static GUIStyle horizontal_line_grey95 { get; private set; }
    public static GUIStyle vertical_line_grey95 { get; private set; }
    public static GUIStyle progressbar_background { get; private set; }
    public static GUIStyle hud_progressbar_background { get; private set; }
    public static GUIStyle progressbar_large_background { get; private set; }
    public static GUIStyle progressbar_large_thumb { get; private set; }
    public static GUIStyle hud_progressbar_thumb { get; private set; }
    public static GUIStyle progressbar_thumb { get; private set; }
    public static GUIStyle mainmenubutton { get; private set; }
    public static GUIStyle mainmenuseparator { get; private set; }
    public static GUIStyle whitebutton { get; private set; }
    public static GUIStyle loadoutdropslot { get; private set; }
    public static GUIStyle loadoutdropslot_highlight { get; private set; }
    public static GUIStyle arrow_small_down { get; private set; }
    public static GUIStyle box_black { get; private set; }
    public static GUIStyle box_white { get; private set; }
    public static GUIStyle friends_listitem { get; private set; }
    public static GUIStyle friends_hidden_button { get; private set; }
    public static GUIStyle friends_contextlink { get; private set; }
    public static GUIStyle button_mainmenu { get; private set; }
    public static GUIStyle button_icontext { get; private set; }
    public static GUIStyle button_right { get; private set; }
    public static GUIStyle button_left { get; private set; }
    public static GUIStyle gray_background { get; private set; }
    
    // Additional properties for LoadRemainingStylesWithErrorHandling
    public static GUIStyle buttongold_small { get; private set; }
    public static GUIStyle buttondark_large { get; private set; }
    public static GUIStyle buttonblue_medium { get; private set; }
    public static GUIStyle buttonblue_small { get; private set; }
    public static GUIStyle playercard_member { get; private set; }
    public static GUIStyle playercard_slot { get; private set; }
    public static GUIStyle playercard_slotweapon { get; private set; }
    public static GUIStyle playercard_slotgear { get; private set; }
    public static GUIStyle playercard_slotquickuse { get; private set; }

    /// <summary>
    /// Safely loads a style from the skin with fallback handling
    /// </summary>
    private static GUIStyle GetSafeStyle(string styleName)
    {
        try
        {
            GUIStyle style = Skin?.GetStyle(styleName);
            if (style != null)
            {
                GUIStyle localizedStyle = LocalizationHelper.GetLocalizedStyle(style);
                return localizedStyle ?? CreateFallbackStyle(styleName);
            }
            else
            {
                UnityEngine.Debug.LogWarning($"Style '{styleName}' not found in BlueStonez skin, using fallback");
                return CreateFallbackStyle(styleName);
            }
        }
        catch (System.Exception ex)
        {
            UnityEngine.Debug.LogError($"Error loading style '{styleName}': {ex.Message}");
            return CreateFallbackStyle(styleName);
        }
    }

    /// <summary>
    /// Creates a basic fallback style when the original is missing
    /// </summary>
    private static GUIStyle CreateFallbackStyle(string styleName)
    {
        GUIStyle fallback = new GUIStyle();
        
        // Set basic properties based on style name
        if (styleName.Contains("label"))
        {
            fallback = new GUIStyle(GUI.skin.label);
        }
        else if (styleName.Contains("button"))
        {
            fallback = new GUIStyle(GUI.skin.button);
        }
        else if (styleName.Contains("box"))
        {
            fallback = new GUIStyle(GUI.skin.box);
        }
        else if (styleName.Contains("window"))
        {
            fallback = new GUIStyle(GUI.skin.window);
        }
        else if (styleName.Contains("progressbar"))
        {
            // Special handling for progressbar styles
            if (styleName.Contains("background"))
            {
                fallback = new GUIStyle();
                fallback.normal.background = Texture2D.whiteTexture;
                fallback.border = new RectOffset(1, 1, 1, 1);
                fallback.padding = new RectOffset(1, 1, 1, 1);
            }
            else if (styleName.Contains("thumb"))
            {
                fallback = new GUIStyle();
                fallback.normal.background = Texture2D.whiteTexture;
                fallback.border = new RectOffset(0, 0, 0, 0);
                fallback.padding = new RectOffset(0, 0, 0, 0);
            }
            else
            {
                fallback = new GUIStyle();
                fallback.normal.background = Texture2D.whiteTexture;
            }
        }
        else
        {
            fallback = new GUIStyle(GUI.skin.label); // Default to label
        }

        // Ensure the fallback style is never null by creating a minimal valid style
        if (fallback == null)
        {
            fallback = new GUIStyle();
        }

        // Set fallback font - prioritize LegacyRuntime.ttf
        Font defaultFont = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        if (defaultFont == null)
        {
            UnityEngine.Debug.LogWarning("LegacyRuntime.ttf not available, falling back to Arial.ttf");
            defaultFont = Resources.GetBuiltinResource<Font>("Arial.ttf");
        }
        
        if (defaultFont != null)
        {
            fallback.font = defaultFont;
        }

        // Handle specific font size requirements based on style name
        if (styleName.Contains("48pt"))
        {
            fallback.fontSize = 48;
        }
        else if (styleName.Contains("32pt"))
        {
            fallback.fontSize = 32;
        }
        else if (styleName.Contains("18pt"))
        {
            fallback.fontSize = 18;
        }
        else if (styleName.Contains("16pt"))
        {
            fallback.fontSize = 16;
        }
        else if (styleName.Contains("13pt"))
        {
            fallback.fontSize = 13;
        }
        else if (styleName.Contains("11pt"))
        {
            fallback.fontSize = 11;
        }
        else if (styleName.Contains("10pt"))
        {
            fallback.fontSize = 10;
        }

        // Handle text alignment for specific styles
        if (styleName.Contains("_left"))
        {
            fallback.alignment = TextAnchor.MiddleLeft;
        }
        else if (styleName.Contains("_right"))
        {
            fallback.alignment = TextAnchor.MiddleRight;
        }
        else if (styleName.Contains("_center"))
        {
            fallback.alignment = TextAnchor.MiddleCenter;
        }

        // Handle font style for bold and medium variants
        if (styleName.Contains("bold"))
        {
            fallback.fontStyle = FontStyle.Bold;
        }
        else if (styleName.Contains("med"))
        {
            fallback.fontStyle = FontStyle.Normal; // Medium weight maps to normal
        }

        // Handle text wrapping
        if (styleName.Contains("wrap"))
        {
            fallback.wordWrap = true;
        }

        return fallback;
    }

    /// <summary>
    /// Gets a safe style that is guaranteed to never be null
    /// </summary>
    public static GUIStyle GetSafeStyleGuaranteed(string styleName)
    {
        GUIStyle style = GetSafeStyle(styleName);
        if (style == null)
        {
            UnityEngine.Debug.LogError($"GetSafeStyle returned null for '{styleName}', creating emergency fallback");
            return new GUIStyle(GUI.skin.label);
        }
        return style;
    }

    /// <summary>
    /// Provides guaranteed non-null progressbar background style
    /// </summary>
    public static GUIStyle SafeProgressBarBackground => progressbar_background ?? CreateProgressBarBackgroundFallback();

    /// <summary>
    /// Provides guaranteed non-null progressbar thumb style
    /// </summary>
    public static GUIStyle SafeProgressBarThumb => progressbar_thumb ?? CreateProgressBarThumbFallback();

    /// <summary>
    /// Provides guaranteed non-null large progressbar background style
    /// </summary>
    public static GUIStyle SafeProgressBarLargeBackground => progressbar_large_background ?? CreateProgressBarBackgroundFallback();

    /// <summary>
    /// Provides guaranteed non-null large progressbar thumb style
    /// </summary>
    public static GUIStyle SafeProgressBarLargeThumb => progressbar_large_thumb ?? CreateProgressBarThumbFallback();

    private static GUIStyle CreateProgressBarBackgroundFallback()
    {
        var style = new GUIStyle();
        style.normal.background = Texture2D.whiteTexture;
        style.border = new RectOffset(1, 1, 1, 1);
        style.padding = new RectOffset(1, 1, 1, 1);
        return style;
    }

    private static GUIStyle CreateProgressBarThumbFallback()
    {
        var style = new GUIStyle();
        style.normal.background = Texture2D.whiteTexture;
        style.border = new RectOffset(0, 0, 0, 0);
        style.padding = new RectOffset(0, 0, 0, 0);
        return style;
    }
}
