/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class BlueStonez
{
    static BlueStonez()
    {
        Skin = Resources.Load("BlueStonez", typeof(GUISkin)) as GUISkin;

        box = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box"));
        label = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label"));
        textField = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("textField"));
        textArea = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("textArea"));
        button = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button"));
        toggle = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("toggle"));
        window = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("window"));
        horizontalSlider = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalSlider"));
        horizontalSliderThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalSliderThumb"));
        verticalSlider = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalSlider"));
        verticalSliderThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalSliderThumb"));
        horizontalScrollbar = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbar"));
        horizontalScrollbarThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarThumb"));
        horizontalScrollbarLeftButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarLeftButton"));
        horizontalScrollbarRightButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarRightButton"));
        verticalScrollbar = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbar"));
        verticalScrollbarThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarThumb"));
        verticalScrollbarUpButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarUpButton"));
        verticalScrollbarDownButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarDownButton"));
        scrollView = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("scrollView"));

        tab_large = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_large"));
        tab_largeicon = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_largeicon"));
        tab_medium = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_medium"));
        dropdown = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("dropdown"));
        tab_strip = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_strip"));
        tab_strip_small = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_strip_small"));
        tab_strip_large = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tab_strip_large"));
        panelstrip_leftbutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("panelstrip_leftbutton"));
        panelstrip_middlebutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("panelstrip_middlebutton"));
        panelstrip_rightbutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("panelstrip_rightbutton"));
        panelquad_button = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("panelquad_button"));
        panelquad_toggle = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("panelquad_toggle"));
        label_interparkbold_32pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_32pt_left"));
        label_interparkbold_32pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_32pt"));
        label_interparkbold_32pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_32pt_right"));
        label_interparkbold_48pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_48pt"));
        label_interparkbold_48pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_48pt_left"));
        label_interparkbold_48pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_48pt_right"));
        label_groupbox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_groupbox"));
        label_group_interparkbold_11pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_group_interparkbold_11pt"));
        label_interparkbold_11pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt"));
        label_interparkbold_11pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt_left"));
        label_interparkbold_11pt_left_wrap = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt_left_wrap"));
        label_interparkbold_11pt_left_wrap_greybg = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt_left_wrap_greybg"));
        label_interparkbold_11pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt_right"));
        label_interparkmed_10pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_10pt_right"));
        label_interparkmed_10pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_10pt_left"));
        label_itemdescription = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_itemdescription"));
        label_interparkbold_16pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_16pt"));
        label_interparkbold_16pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_16pt_left"));
        label_interparkbold_16pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_16pt_right"));
        label_interparkbold_18pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_18pt_left"));
        label_interparkbold_18pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_18pt_right"));
        label_interparkbold_18pt_right_white = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_18pt_right_white"));
        label_interparkmed_18pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_18pt_right"));
        label_interparkmed_18pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_18pt_left"));
        label_interparkmed_18pt_left_wrap = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_18pt_left_wrap"));
        label_ingamechat = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_ingamechat"));
        box_grey31 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_grey31"));
        box_grey38 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_grey38"));
        box_white_2px = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_white_2px"));
        box_grey_outlined = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_grey_outlined"));
        box_grey_outlined_tip = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_grey_outlined_tip"));
        box_white_rounded = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_white_rounded"));
        window_standard_grey38 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("window_standard_grey38"));
        group_grey81 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("group_grey81"));
        label_group_interparkbold_18pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_group_interparkbold_18pt"));
        label_interparkbold_18pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_18pt"));
        radiobutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("radiobutton"));
        ingamechat = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ingamechat"));
        speechbubble_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("speechbubble_left"));
        speechbubble_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("speechbubble_right"));
        tooltip = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("tooltip"));
        label_interparkmed_11pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_11pt"));
        label_interparkmed_11pt_middleLeft = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_11pt_middleLeft"));
        label_interparkmed_11pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_11pt_left"));
        label_interparkmed_11pt_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_11pt_right"));
        label_interparkmed_11pt_url = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkmed_11pt_url"));
        label_interparkbold_11pt_url = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_11pt_url"));
        label_interparkbold_13pt = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_13pt"));
        label_interparkbold_13pt_black = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_13pt_black"));
        label_interparkbold_13pt_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_interparkbold_13pt_left"));
        dropdown_button = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("dropdown_button"));
        button_context = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_context"));
        label_dropdown = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label_dropdown"));
        box_grey50 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_grey50"));
        packslot = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("packslot"));
        box_overlay = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_overlay"));
        box_overlay_black = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_overlay_black"));
        dropdown_list = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("dropdown_list"));
        dropdown_listItem = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("dropdown_listItem"));
        buttondark_medium = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("buttondark_medium"));
        button_fbconnect = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_fbconnect"));
        buttongold_medium = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("buttongold_medium"));
        buttongold_large_price = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("buttongold_large_price"));
        buttongold_large = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("buttongold_large"));
        button_white = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_white"));
        button_green = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_green"));
        button_red = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_red"));
        buttondark_small = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("buttondark_small"));
        toggle_item_slot = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("toggle_item_slot"));
        item_slot_64 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("item_slot_64"));
        item_slot_large = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("item_slot_large"));
        item_slot_alpha = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("item_slot_alpha"));
        item_slot_small = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("item_slot_small"));
        horizontal_line_grey95 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontal_line_grey95"));
        vertical_line_grey95 = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("vertical_line_grey95"));
        progressbar_background = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("progressbar_background"));
        hud_progressbar_background = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("hud_progressbar_background"));
        progressbar_large_background = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("progressbar_large_background"));
        progressbar_large_thumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("progressbar_large_thumb"));
        hud_progressbar_thumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("hud_progressbar_thumb"));
        progressbar_thumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("progressbar_thumb"));
        mainmenubutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("mainmenubutton"));
        mainmenuseparator = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("mainmenuseparator"));
        whitebutton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("whitebutton"));
        loadoutdropslot = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("loadoutdropslot"));
        loadoutdropslot_highlight = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("loadoutdropslot_highlight"));
        arrow_small_down = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("arrow_small_down"));
        box_black = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_black"));
        box_white = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box_white"));
        friends_listitem = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("friends_listitem"));
        friends_hidden_button = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("friends_hidden_button"));
        friends_contextlink = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("friends_contextlink"));
        button_mainmenu = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_mainmenu"));
        button_icontext = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_icontext"));
        button_right = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_right"));
        button_left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button_left"));
        gray_background = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("gray_background"));
        dropdown_large = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("dropdown_large"));
    }

    public static GUISkin Skin { get; private set; }

    public static GUIStyle box { get; private set; }
    public static GUIStyle label { get; private set; }
    public static GUIStyle textField { get; private set; }
    public static GUIStyle textArea { get; private set; }
    public static GUIStyle button { get; private set; }
    public static GUIStyle toggle { get; private set; }
    public static GUIStyle window { get; private set; }
    public static GUIStyle horizontalSlider { get; private set; }
    public static GUIStyle horizontalSliderThumb { get; private set; }
    public static GUIStyle verticalSlider { get; private set; }
    public static GUIStyle verticalSliderThumb { get; private set; }
    public static GUIStyle horizontalScrollbar { get; private set; }
    public static GUIStyle horizontalScrollbarThumb { get; private set; }
    public static GUIStyle horizontalScrollbarLeftButton { get; private set; }
    public static GUIStyle horizontalScrollbarRightButton { get; private set; }
    public static GUIStyle verticalScrollbar { get; private set; }
    public static GUIStyle verticalScrollbarThumb { get; private set; }
    public static GUIStyle verticalScrollbarUpButton { get; private set; }
    public static GUIStyle verticalScrollbarDownButton { get; private set; }
    public static GUIStyle scrollView { get; private set; }

    public static GUIStyle tab_large { get; private set; }
    public static GUIStyle tab_largeicon { get; private set; }
    public static GUIStyle tab_medium { get; private set; }
    public static GUIStyle dropdown { get; private set; }
    public static GUIStyle tab_strip { get; private set; }
    public static GUIStyle tab_strip_small { get; private set; }
    public static GUIStyle tab_strip_large { get; private set; }
    public static GUIStyle panelstrip_leftbutton { get; private set; }
    public static GUIStyle panelstrip_middlebutton { get; private set; }
    public static GUIStyle panelstrip_rightbutton { get; private set; }
    public static GUIStyle panelquad_button { get; private set; }
    public static GUIStyle panelquad_toggle { get; private set; }
    public static GUIStyle label_interparkbold_32pt_left { get; private set; }
    public static GUIStyle label_interparkbold_32pt { get; private set; }
    public static GUIStyle label_interparkbold_32pt_right { get; private set; }
    public static GUIStyle label_interparkbold_48pt { get; private set; }
    public static GUIStyle label_interparkbold_48pt_left { get; private set; }
    public static GUIStyle label_interparkbold_48pt_right { get; private set; }
    public static GUIStyle label_groupbox { get; private set; }
    public static GUIStyle label_group_interparkbold_11pt { get; private set; }
    public static GUIStyle label_interparkbold_11pt { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left_wrap { get; private set; }
    public static GUIStyle label_interparkbold_11pt_left_wrap_greybg { get; private set; }
    public static GUIStyle label_interparkbold_11pt_right { get; private set; }
    public static GUIStyle label_interparkmed_10pt_right { get; private set; }
    public static GUIStyle label_interparkmed_10pt_left { get; private set; }
    public static GUIStyle label_itemdescription { get; private set; }
    public static GUIStyle label_interparkbold_16pt { get; private set; }
    public static GUIStyle label_interparkbold_16pt_left { get; private set; }
    public static GUIStyle label_interparkbold_16pt_right { get; private set; }
    public static GUIStyle label_interparkbold_18pt_left { get; private set; }
    public static GUIStyle label_interparkbold_18pt_right { get; private set; }
    public static GUIStyle label_interparkbold_18pt_right_white { get; private set; }
    public static GUIStyle label_interparkmed_18pt_right { get; private set; }
    public static GUIStyle label_interparkmed_18pt_left { get; private set; }
    public static GUIStyle label_interparkmed_18pt_left_wrap { get; private set; }
    public static GUIStyle label_ingamechat { get; private set; }
    public static GUIStyle box_grey31 { get; private set; }
    public static GUIStyle box_grey38 { get; private set; }
    public static GUIStyle box_white_2px { get; private set; }
    public static GUIStyle box_grey_outlined { get; private set; }
    public static GUIStyle box_grey_outlined_tip { get; private set; }
    public static GUIStyle box_white_rounded { get; private set; }
    public static GUIStyle window_standard_grey38 { get; private set; }
    public static GUIStyle group_grey81 { get; private set; }
    public static GUIStyle label_group_interparkbold_18pt { get; private set; }
    public static GUIStyle label_interparkbold_18pt { get; private set; }
    public static GUIStyle radiobutton { get; private set; }
    public static GUIStyle ingamechat { get; private set; }
    public static GUIStyle speechbubble_left { get; private set; }
    public static GUIStyle speechbubble_right { get; private set; }
    public static GUIStyle tooltip { get; private set; }
    public static GUIStyle label_interparkmed_11pt { get; private set; }
    public static GUIStyle label_interparkmed_11pt_middleLeft { get; private set; }
    public static GUIStyle label_interparkmed_11pt_left { get; private set; }
    public static GUIStyle label_interparkmed_11pt_right { get; private set; }
    public static GUIStyle label_interparkmed_11pt_url { get; private set; }
    public static GUIStyle label_interparkbold_11pt_url { get; private set; }
    public static GUIStyle label_interparkbold_13pt { get; private set; }
    public static GUIStyle label_interparkbold_13pt_black { get; private set; }
    public static GUIStyle label_interparkbold_13pt_left { get; private set; }
    public static GUIStyle dropdown_button { get; private set; }
    public static GUIStyle button_context { get; private set; }
    public static GUIStyle label_dropdown { get; private set; }
    public static GUIStyle box_grey50 { get; private set; }
    public static GUIStyle packslot { get; private set; }
    public static GUIStyle box_overlay { get; private set; }
    public static GUIStyle box_overlay_black { get; private set; }
    public static GUIStyle dropdown_list { get; private set; }
    public static GUIStyle dropdown_listItem { get; private set; }
    public static GUIStyle buttondark_medium { get; private set; }
    public static GUIStyle button_fbconnect { get; private set; }
    public static GUIStyle buttongold_medium { get; private set; }
    public static GUIStyle buttongold_large_price { get; private set; }
    public static GUIStyle buttongold_large { get; private set; }
    public static GUIStyle button_white { get; private set; }
    public static GUIStyle button_green { get; private set; }
    public static GUIStyle button_red { get; private set; }
    public static GUIStyle buttondark_small { get; private set; }
    public static GUIStyle toggle_item_slot { get; private set; }
    public static GUIStyle item_slot_64 { get; private set; }
    public static GUIStyle item_slot_large { get; private set; }
    public static GUIStyle item_slot_alpha { get; private set; }
    public static GUIStyle item_slot_small { get; private set; }
    public static GUIStyle horizontal_line_grey95 { get; private set; }
    public static GUIStyle vertical_line_grey95 { get; private set; }
    public static GUIStyle progressbar_background { get; private set; }
    public static GUIStyle hud_progressbar_background { get; private set; }
    public static GUIStyle progressbar_large_background { get; private set; }
    public static GUIStyle progressbar_large_thumb { get; private set; }
    public static GUIStyle hud_progressbar_thumb { get; private set; }
    public static GUIStyle progressbar_thumb { get; private set; }
    public static GUIStyle mainmenubutton { get; private set; }
    public static GUIStyle mainmenuseparator { get; private set; }
    public static GUIStyle whitebutton { get; private set; }
    public static GUIStyle loadoutdropslot { get; private set; }
    public static GUIStyle loadoutdropslot_highlight { get; private set; }
    public static GUIStyle arrow_small_down { get; private set; }
    public static GUIStyle box_black { get; private set; }
    public static GUIStyle box_white { get; private set; }
    public static GUIStyle friends_listitem { get; private set; }
    public static GUIStyle friends_hidden_button { get; private set; }
    public static GUIStyle friends_contextlink { get; private set; }
    public static GUIStyle button_mainmenu { get; private set; }
    public static GUIStyle button_icontext { get; private set; }
    public static GUIStyle button_right { get; private set; }
    public static GUIStyle button_left { get; private set; }
    public static GUIStyle gray_background { get; private set; }
    public static GUIStyle dropdown_large { get; private set; }
}
