using UnityEngine;

/// <summary>
/// Silences the per-frame IMGUI warning "Font size and style overrides are only supported for dynamic
/// fonts." The BlueStonez/StormFront skins ship many interpark* label styles whose font is a BITMAP
/// (non-dynamic) font but which still carry a fontSize / fontStyle override. IMGUI can't apply those
/// overrides to a bitmap font, so it logs the warning on EVERY CalcSize/draw of such a style — and the
/// shop / Weekly-Special price rows (BaseItemGUI.DrawPrice, redrawn every OnGUI) flooded the device log
/// ~900x per session (512 from the Weekly Special alone).
///
/// The override was already being ignored, so clearing it is visually identical — the bitmap font keeps
/// rendering at its baked size. We only touch styles whose EFFECTIVE font is non-dynamic, so localized
/// (CJK) builds that legitimately swap in a dynamic font + a real fontSize are left untouched.
///
/// Runs once at startup (BeforeSceneLoad) and is idempotent, so the manual verifier can also call Apply().
/// Lives outside the autogenerated BlueStonez.cs / StormFront.cs (which warn "changes will be lost").
/// </summary>
public static class GuiFontOverrideFix
{
    private static bool _applied;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    public static void Apply()
    {
        if (_applied) return;
        _applied = true;
        NeutralizeAll();
    }

    /// <summary>Unguarded worker — neutralizes inert bitmap-font overrides on both skins. Idempotent.</summary>
    public static void NeutralizeAll()
    {
        NeutralizeSkin(BlueStonez.Skin);
        NeutralizeSkin(StormFront.Skin);
    }

    private static void NeutralizeSkin(GUISkin skin)
    {
        if (skin == null) return;
        Font def = skin.font;

        // Built-in styles
        Neutralize(skin.box, def);
        Neutralize(skin.label, def);
        Neutralize(skin.textField, def);
        Neutralize(skin.textArea, def);
        Neutralize(skin.button, def);
        Neutralize(skin.toggle, def);
        Neutralize(skin.window, def);
        Neutralize(skin.horizontalSlider, def);
        Neutralize(skin.horizontalSliderThumb, def);
        Neutralize(skin.verticalSlider, def);
        Neutralize(skin.verticalSliderThumb, def);
        Neutralize(skin.horizontalScrollbar, def);
        Neutralize(skin.verticalScrollbar, def);
        Neutralize(skin.scrollView, def);

        // Custom styles (where the interpark* label styles live)
        if (skin.customStyles != null)
        {
            foreach (GUIStyle s in skin.customStyles)
                Neutralize(s, def);
        }
    }

    private static void Neutralize(GUIStyle s, Font skinFont)
    {
        if (s == null) return;
        Font f = s.font != null ? s.font : skinFont; // effective font IMGUI will draw with
        if (f != null && !f.dynamic && (s.fontSize != 0 || s.fontStyle != FontStyle.Normal))
        {
            s.fontSize = 0;
            s.fontStyle = FontStyle.Normal;
        }
    }
}
