/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class StormFront
{
    static StormFront()
    {
        Skin = Resources.Load("StormFront", typeof(GUISkin)) as GUISkin;

        box = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("box"));
        label = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("label"));
        textField = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("textField"));
        textArea = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("textArea"));
        button = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("button"));
        toggle = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("toggle"));
        window = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("window"));
        horizontalSlider = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalSlider"));
        horizontalSliderThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalSliderThumb"));
        verticalSlider = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalSlider"));
        verticalSliderThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalSliderThumb"));
        horizontalScrollbar = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbar"));
        horizontalScrollbarThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarThumb"));
        horizontalScrollbarLeftButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarLeftButton"));
        horizontalScrollbarRightButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("horizontalScrollbarRightButton"));
        verticalScrollbar = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbar"));
        verticalScrollbarThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarThumb"));
        verticalScrollbarUpButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarUpButton"));
        verticalScrollbarDownButton = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("verticalScrollbarDownButton"));
        scrollView = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("scrollView"));

        BlueBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("BlueBox"));
        RedBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("RedBox"));
        BluePanelBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("BluePanelBox"));
        GrayPanelBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("GrayPanelBox"));
        GrayPanelBlankBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("GrayPanelBlankBox"));
        RedPanelBox = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("RedPanelBox"));
        ButtonRed = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonRed"));
        ButtonBlue = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonBlue"));
        ButtonGray = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonGray"));
        ButtonJoinBlue = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonJoinBlue"));
        ButtonJoinRed = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonJoinRed"));
        ButtonJoinGray = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonJoinGray"));
        ButtonSpectator = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonSpectator"));
        ButtonLoadout = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonLoadout"));
        ButtonLoadoutRed = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonLoadoutRed"));
        InGameChatBlue = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("InGameChatBlue"));
        InGameChatRed = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("InGameChatRed"));
        DotBlue = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("DotBlue"));
        DotRed = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("DotRed"));
        DotGray = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("DotGray"));
        ButtonCam = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ButtonCam"));
        Interpark32Center = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("Interpark32Center"));
        Interpark16Left = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("Interpark16Left"));
        ProgressBackground = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ProgressBackground"));
        ProgressForeground = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ProgressForeground"));
        ProgressThumb = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle("ProgressThumb"));
    }

    public static GUISkin Skin { get; private set; }

    public static GUIStyle box { get; private set; }
    public static GUIStyle label { get; private set; }
    public static GUIStyle textField { get; private set; }
    public static GUIStyle textArea { get; private set; }
    public static GUIStyle button { get; private set; }
    public static GUIStyle toggle { get; private set; }
    public static GUIStyle window { get; private set; }
    public static GUIStyle horizontalSlider { get; private set; }
    public static GUIStyle horizontalSliderThumb { get; private set; }
    public static GUIStyle verticalSlider { get; private set; }
    public static GUIStyle verticalSliderThumb { get; private set; }
    public static GUIStyle horizontalScrollbar { get; private set; }
    public static GUIStyle horizontalScrollbarThumb { get; private set; }
    public static GUIStyle horizontalScrollbarLeftButton { get; private set; }
    public static GUIStyle horizontalScrollbarRightButton { get; private set; }
    public static GUIStyle verticalScrollbar { get; private set; }
    public static GUIStyle verticalScrollbarThumb { get; private set; }
    public static GUIStyle verticalScrollbarUpButton { get; private set; }
    public static GUIStyle verticalScrollbarDownButton { get; private set; }
    public static GUIStyle scrollView { get; private set; }

    public static GUIStyle BlueBox { get; private set; }
    public static GUIStyle RedBox { get; private set; }
    public static GUIStyle BluePanelBox { get; private set; }
    public static GUIStyle GrayPanelBox { get; private set; }
    public static GUIStyle GrayPanelBlankBox { get; private set; }
    public static GUIStyle RedPanelBox { get; private set; }
    public static GUIStyle ButtonRed { get; private set; }
    public static GUIStyle ButtonBlue { get; private set; }
    public static GUIStyle ButtonGray { get; private set; }
    public static GUIStyle ButtonJoinBlue { get; private set; }
    public static GUIStyle ButtonJoinRed { get; private set; }
    public static GUIStyle ButtonJoinGray { get; private set; }
    public static GUIStyle ButtonSpectator { get; private set; }
    public static GUIStyle ButtonLoadout { get; private set; }
    public static GUIStyle ButtonLoadoutRed { get; private set; }
    public static GUIStyle InGameChatBlue { get; private set; }
    public static GUIStyle InGameChatRed { get; private set; }
    public static GUIStyle DotBlue { get; private set; }
    public static GUIStyle DotRed { get; private set; }
    public static GUIStyle DotGray { get; private set; }
    public static GUIStyle ButtonCam { get; private set; }
    public static GUIStyle Interpark32Center { get; private set; }
    public static GUIStyle Interpark16Left { get; private set; }
    public static GUIStyle ProgressBackground { get; private set; }
    public static GUIStyle ProgressForeground { get; private set; }
    public static GUIStyle ProgressThumb { get; private set; }
}
