/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System.Collections.Generic;

/// <summary>
/// Here we provide data for consistency checks and editor scripts
/// </summary>
public static class BackendData
{
		// 1045, 10, 	10, 	"Iron Pants of Resistance"
		// 1098, 140, 	100, 	"Admin Shirt"
		// 1099, 50, 	50, 	"Beta Hero"
		// 1101, 30, 	30, 	"SForce Ninja Armor"
		// 1102, 30, 	30, 	"SForce Ninja Greaves"
		// 1111, 20, 	20, 	"Cap'n Bradford's Jacket"
		// 1112, 20, 	20, 	"Cap'n Bradford's Pants"
		// 1117, 10, 	10, 	"The Muscle Suit"
		// 1118, 10, 	10, 	"The Jeans of Manliness"
		// 1121, 20, 	20, 	"The Croc Skin Jacket"
		// 1122, 20, 	20, 	"The Croc Skin Pants"
		// 1140, 15, 	15, 	"The Bone Cage"
		// 1141, 15, 	15, 	"Lifeless Legs"
		// 1151, 30, 	30, 	"Black Suit Pants"
		// 1152, 20, 	20, 	"Grey Suit Pants"
		// 1153, 30, 	30, 	"SuperSpy Jacket"
		// 1155, 60, 	40, 	"Godfather's Suit Jacket"
		// 1156, 10, 	10, 	"Luxury Leather Coat"
		// 1158, 20, 	20, 	"Doctor Death"
		// 1159, 20, 	20, 	"Mafioso Jacket"
		// 1167, 30, 	30, 	"Sir Magnus Cuirass"
		// 1168, 30, 	30, 	"Sir Magnus Greaves"
		// 1174, 40, 	40, 	"Iron Body of Viktor"
		// 1175, 40, 	40, 	"Iron Legs of Viktor"
		// 1185, 20, 	20, 	"UberSanta Jacket"
		// 1186, 20, 	20, 	"UberSanta Pants"
		// 1227, 30, 	30, 	"T500 Blue Legs"
		// 1228, 30, 	30, 	"T500 Red Legs"
		// 1229, 10, 	10, 	"T500 Yellow Legs"
		// 1230, 25, 	25, 	"T500 Blue Armor"
		// 1231, 30, 	30, 	"T500 Red Armor"
		// 1232, 10, 	10, 	"T500 Yellow Armor"
		// 1254, 50, 	50, 	"Mod Shirt"
		// 1255, 50, 	50, 	"Global Mod Shirt"
		// 1260, 30, 	30, 	"ArcticDreads Tactical Pants"
		// 1261, 30, 	30, 	"ArcticDreads Tactical Jacket"
		// 1263, 30, 	30, 	"Eco Shirt"
		// 1276, 40, 	40, 	"Black Corps Leg Armor"
		// 1277, 40, 	40, 	"Black Corps Body Armor"
		// 1281, 40, 	40, 	"Juggernaut Leg Armor"
		// 1282, 40, 	40, 	"Juggernaut Chest Armor"
		// 1287, 40, 	40, 	"Sentinel Power Greaves"
		// 1288, 40, 	40, 	"Sentinel Power Armor"
		// 1289, 20, 	40, 	"Cyber Zombie Lutz"
		// 1290, 5, 	40, 	"Zombie Lutz"
		// 1304, 40, 	40, 	"Juggernaut Chest Dragon Edition"
		// 1305, 40, 	40, 	"Juggernaut Legs Dragon Edition"
		// 1310, 20, 	40, 	"Julia Ninja holo"
		// 1319, 40, 	40, 	"Ninja Armor Black Dragon Edition"
		// 1320, 40, 	40, 	"Ninja Greaves Black Dragon Edition "
		// 1325, 40, 	40, 	"Ninja Armor White Dragon Edition"
		// 1326, 40, 	40, 	"Ninja Greaves White Dragon Edition "
		// 1332, 40, 	40, 	"Kongregate Power Armor"
		// 1333, 40, 	40, 	"Kongregate Power Greaves"
		// 1338, 40, 	40, 	"Kongregate Jacket Advanced"
		// 1342, 60, 	20, 	"Mantle of Lucius the Cruel"
		// 1343, 60, 	20, 	"Drawers of Lucius the Cruel"
		// 1399, 60, 	20, 	"Terrorist Vest"
		// 1400, 60, 	20, 	"Terrorist Pants Urban"
	public static readonly Dictionary<int, string> SupportedItems = new Dictionary<int, string>() {
		{ 1000, "Splatbat" },	
		{ 1001, "Handgun" },	
		{ 1002, "Machine Gun" },	
		{ 1003, "Shotgun" },	
		{ 1004, "Sniper Rifle" },	
		{ 1005, "Cannon" },	
		{ 1006, "Splatter Gun" },	
		{ 1007, "Grenade Launcher" },	
		{ 1008, "Judge" },	
		{ 1009, "Jury" },	
		{ 1010, "Executioner" },	
		{ 1011, "Shadow Gun" },	
		{ 1012, "Battlesnake" },	
		{ 1013, "Snotgun" },	
		{ 1014, "Pain Hammer" },	
		{ 1015, "Thunderbuss" },	
		{ 1016, "Ordinator Rifle" },	
		{ 1017, "Deliverator" },	
		{ 1018, "Vanquisher" },	
		{ 1019, "Painzerfaust" },	
		{ 1020, "Force Cannon" },	
		{ 1021, "Vandalizer" },	
		{ 1022, "Mad Splatter" },	
		{ 1023, "Magma Rifle" },	
		{ 1024, "Enamelator" },	
		{ 1025, "Mortar Exporter" },	
		{ 1026, "The Final Word" },	
		{ 1031, "Sunglasses" },	
		{ 1033, "Beard and Mo" },	
		{ 1045, "Iron Pants of Resistance" },	
		{ 1051, "Jungle Camo Pants" },	
		{ 1053, "Black Hair" },	
		{ 1054, "Blue Hair" },	
		{ 1055, "Red Hair" },	
		{ 1075, "Green Beret" },	
		{ 1084, "Default Hair" },	
		{ 1085, "Default Goggles" },	
		{ 1086, "Default Gloves" },	
		{ 1087, "Jacket of Boredom" },	
		{ 1088, "Trousers of Tedium" },	
		{ 1089, "Ordinary Boots" },	
		{ 1094, "Privateer License" },	
		{ 1098, "Admin Shirt" },	
		{ 1099, "Beta Hero" },	
		{ 1100, "Green Shirt" },	
		{ 1101, "SForce Ninja Armor" },	
		{ 1102, "SForce Ninja Greaves" },	
		{ 1103, "SForce Ninja Headband" },	
		{ 1104, "SForce Ninja Mask" },	
		{ 1105, "SForce Ninja Maw" },	
		{ 1106, "SForce Ninja Claws" },	
		{ 1107, "SForce Ninja Tabi" },	
		{ 1108, "Cap'n Bradford's Hat" },	
		{ 1109, "Cap'n Bradford's Patch" },	
		{ 1110, "Cap'n Bradford's Gloves" },	
		{ 1111, "Cap'n Bradford's Jacket" },	
		{ 1112, "Cap'n Bradford's Pants" },	
		{ 1113, "Cap'n Bradford's Boots" },	
		{ 1114, "Red Pirate Bandanna" },	
		{ 1115, "The Commandanna" },	
		{ 1116, "The Goon Crushers" },	
		{ 1117, "The Muscle Suit" },	
		{ 1118, "The Jeans of Manliness" },	
		{ 1119, "The Tramplers" },	
		{ 1120, "The Croc Skin Akubra" },	
		{ 1121, "The Croc Skin Jacket" },	
		{ 1122, "The Croc Skin Pants" },	
		{ 1123, "The Croc Skin Boots" },	
		{ 1136, "Mythic Edge" },	
		{ 1137, "Pumpkin o' Gloom" },	
		{ 1138, "The White Skull" },	
		{ 1139, "Mask of Terror" },	
		{ 1140, "The Bone Cage" },	
		{ 1141, "Lifeless Legs" },	
		{ 1142, "The Harvester of Noobs" },	
		{ 1143, "Cadaverous Claws" },	
		{ 1144, "Skeletal Shoes" },	
		{ 1145, "Enigma Cannon" },	
		{ 1146, "UMG" },	
		{ 1147, "Particle Lance" },	
		{ 1148, "The Croc Cutter" },	
		{ 1149, "Stalwart Steel" },	
		{ 1150, "Bradford's Broadsword" },	
		{ 1151, "Black Suit Pants" },	
		{ 1152, "Grey Suit Pants" },	
		{ 1153, "SuperSpy Jacket" },	
		{ 1154, "Classy Coat" },	
		{ 1155, "Godfather's Suit Jacket" },	
		{ 1156, "Luxury Leather Coat" },	
		{ 1157, "Leather Dress Shoes" },	
		{ 1158, "Doctor Death" },	
		{ 1159, "Mafioso Jacket" },	
		{ 1162, "UberHammer" },	
		{ 1163, "UberJacket" },	
		{ 1164, "Godfather's Hand Cannon" },	
		{ 1165, "Chibi Boy" },	
		{ 1166, "Chibi Girl" },	
		{ 1167, "Sir Magnus Cuirass" },	
		{ 1168, "Sir Magnus Greaves" },	
		{ 1169, "Sir Magnus Gauntlets" },	
		{ 1170, "Sir Magnus Boots" },	
		{ 1171, "Sir Magnus Horned Helmet" },	
		{ 1172, "Sir Magnus Thorny Helmet" },	
		{ 1173, "Sir Magnus Crested Helmet" },	
		{ 1174, "Iron Body of Viktor" },	
		{ 1175, "Iron Legs of Viktor" },	
		{ 1176, "Iron Fists of Viktor" },	
		{ 1177, "Iron Heel of Viktor" },	
		{ 1178, "Iron Horns of Viktor" },	
		{ 1179, "Iron Helmet of Viktor" },	
		{ 1180, "Iron Crest of Viktor" },	
		{ 1184, "UberSanta Claw" },	
		{ 1185, "UberSanta Jacket" },	
		{ 1186, "UberSanta Pants" },	
		{ 1187, "UberSanta Hat" },	
		{ 1188, "UberSanta Gloves" },	
		{ 1189, "UberSanta Boots" },	
		{ 1190, "UberBeard" },	
		{ 1191, "Australia Mask" },	
		{ 1192, "Brazil Mask" },	
		{ 1193, "Canada Mask" },	
		{ 1194, "China Mask" },	
		{ 1195, "Europe Mask" },	
		{ 1196, "France Mask" },	
		{ 1197, "Germany Mask" },	
		{ 1198, "Holland Mask" },	
		{ 1199, "Hong Kong Mask" },	
		{ 1200, "India Mask" },	
		{ 1201, "Italy Mask" },	
		{ 1202, "Japan Mask" },	
		{ 1203, "Latvia Mask" },	
		{ 1204, "Malaysia Mask" },	
		{ 1205, "Mexico Mask" },	
		{ 1206, "New Zealand Mask" },	
		{ 1207, "Philippines Mask" },	
		{ 1208, "Poland Mask" },	
		{ 1209, "Portugal Mask" },	
		{ 1210, "Romania Mask" },	
		{ 1211, "Russia Mask" },	
		{ 1212, "Singapore Mask" },	
		{ 1213, "South Korea Mask" },	
		{ 1214, "Spain Mask" },	
		{ 1215, "Turkey Mask" },	
		{ 1216, "UK Mask" },	
		{ 1217, "USA Mask" },	
		{ 1218, "T500 Blue Boots" },	
		{ 1219, "T500 Red Boots" },	
		{ 1220, "T500 Yellow Boots" },	
		{ 1221, "T500 Blue Gloves" },	
		{ 1222, "T500 Red Gloves" },	
		{ 1223, "T500 Yellow Gloves" },	
		{ 1224, "T500 Blue Mask" },	
		{ 1225, "T500 Red Mask" },	
		{ 1226, "T500 Yellow Mask" },	
		{ 1227, "T500 Blue Legs" },	
		{ 1228, "T500 Red Legs" },	
		{ 1229, "T500 Yellow Legs" },	
		{ 1230, "T500 Blue Armor" },	
		{ 1231, "T500 Red Armor" },	
		{ 1232, "T500 Yellow Armor" },	
		{ 1233, "Taiwan Mask" },	
		{ 1234, "Clan License" },	
		{ 1237, "Spiteful Stinger" },	
		{ 1239, "Nefarious Needler" },	
		{ 1240, "Julia Holo" },	
		{ 1241, "Sabertooth" },	
		{ 1242, "Firewave" },	
		{ 1243, "Force Cannon Plus" },	
		{ 1244, "Dark Vanquisher" },	
		{ 1245, "Arctic Rifle" },	
		{ 1246, "Fusion Lance" },	
		{ 1247, "Spring Grenades: 3" },	
		{ 1248, "Spring Grenades: 1" },	
		{ 1249, "Spring Grenades: 8" },	
		{ 1254, "Mod Shirt" },	
		{ 1255, "Global Mod Shirt" },	
		{ 1256, "ArcticDreads Boots" },	
		{ 1257, "ArcticDreads Mask" },	
		{ 1258, "ArcticDreads Gloves" },	
		{ 1259, "ArcticDreads Beanie" },	
		{ 1260, "ArcticDreads Tactical Pants" },	
		{ 1261, "ArcticDreads Tactical Jacket" },	
		{ 1262, "iLauncher" },	
		{ 1263, "Eco Shirt" },	
		{ 1265, "App License" },	
		{ 1272, "Black Corps Boots" },	
		{ 1273, "Black Corps Balaclava" },	
		{ 1274, "Black Corps Gloves" },	
		{ 1275, "Black Corps Helmet" },	
		{ 1276, "Black Corps Leg Armor" },	
		{ 1277, "Black Corps Body Armor" },	
		{ 1278, "Juggernaut Boots" },	
		{ 1279, "Juggernaut Powered Grip" },	
		{ 1280, "Juggernaut Visor" },	
		{ 1281, "Juggernaut Leg Armor" },	
		{ 1282, "Juggernaut Chest Armor" },	
		{ 1283, "Sentinel Spurs" },	
		{ 1285, "Sentinel Gloves" },	
		{ 1286, "Sentinel Cowl" },	
		{ 1287, "Sentinel Power Greaves" },	
		{ 1288, "Sentinel Power Armor" },	
		{ 1289, "Cyber Zombie Lutz" },	
		{ 1290, "Zombie Lutz" },	
		{ 1291, "Death Hammer" },	
		{ 1292, "Oblivion Hammer" },	
		{ 1293, "The Sender" },	
		{ 1294, "Name Change" },	
		{ 1297, "Demolisher" },	
		{ 1298, "Vlad" },	
		{ 1299, "Ultima Cannon" },	
		{ 1300, "Snap Shot" },	
		{ 1301, "Vanquisher Dragon Edition" },	
		{ 1302, "Magma Rifle Dragon Edition" },	
		{ 1303, "UMG Dragon Edition" },	
		{ 1304, "Juggernaut Chest Dragon Edition" },	
		{ 1305, "Juggernaut Legs Dragon Edition" },	
		{ 1307, "Juggernaut's Grip Dragon Edition" },	
		{ 1308, "Juggernaut Boots Dragon Edition" },	
		{ 1309, "Juggernaut Visor Dragon Edition" },	
		{ 1310, "Julia Ninja holo" },	
		{ 1311, "The Love Gun" },	
		{ 1312, "Mythic Edge Dragon Edition" },	
		{ 1313, "Battlesnake Dragon Edition" },	
		{ 1314, "Thunderbuss Dragon Edition" },	
		{ 1315, "Enigma Cannon Dragon Edition" },	
		{ 1316, "Particle Lance Dragon Edition" },	
		{ 1319, "Ninja Armor Black Dragon Edition" },	
		{ 1320, "Ninja Greaves Black Dragon Edition " },	
		{ 1321, "Ninja Headband Black Dragon Edition" },	
		{ 1322, "Ninja Maw Black Dragon Edition" },	
		{ 1323, "Ninja Claws Black Dragon Edition" },	
		{ 1324, "Ninja Tabi Black Dragon Edition" },	
		{ 1325, "Ninja Armor White Dragon Edition" },	
		{ 1326, "Ninja Greaves White Dragon Edition " },	
		{ 1327, "Ninja Headband White Dragon Edition" },	
		{ 1328, "Ninja Maw White Dragon Edition" },	
		{ 1329, "Ninja Claws White Dragon Edition" },	
		{ 1330, "Ninja Tabi White Dragon Edition" },	
		{ 1331, "Vanquisher Kongregate Edition" },	
		{ 1332, "Kongregate Power Armor" },	
		{ 1333, "Kongregate Power Greaves" },	
		{ 1334, "Kongregate Cowl" },	
		{ 1335, "Kongregate Gloves" },	
		{ 1336, "Kongregate Spurs" },	
		{ 1337, "Kongregate Jacket Basic" },	
		{ 1338, "Kongregate Jacket Advanced" },	
		{ 1339, "Coiffure of Lucius the Cruel" },	
		{ 1340, "Fangs of Lucius  the Cruel" },	
		{ 1341, "Gloves of Lucius the Cruel" },	
		{ 1342, "Mantle of Lucius the Cruel" },	
		{ 1343, "Drawers of Lucius the Cruel" },	
		{ 1344, "Boots of Lucius the Cruel" },	
		{ 1345, "INSTANT HEAL" },	
		{ 1346, "HEAL OVER TIME" },	
		{ 1347, "HEAL AFTER FOCUS" },	
		{ 1349, "Cannon Ammo Buff" },	
		{ 1350, "Armor Buff" },	
		{ 1351, "Default Grenade" },	
		{ 1355, "AWP Normal" },	
		{ 1356, "AWP Black" },	
		{ 1357, "Awp Camouflage" },	
		{ 1358, "AWP \"Tiger Stripes\"" },	
		{ 1359, "UZI \"Normal\"" },	
		{ 1360, "UZI \"Camouflage\"" },	
		{ 1361, "UZI \"Tiger Stripes\"" },	
		{ 1362, "UZI \"Gold\"" },	
		{ 1363, "USP \"Normal\"" },	
		{ 1364, "USP \"Camouflage\"" },	
		{ 1365, "USP \"Black\"" },	
		{ 1366, "USP \"Tiger Stripes\"" },	
		{ 1367, "USP Silenced \"Normal\"" },	
		{ 1368, "USP Silenced \"Camouflage\"" },	
		{ 1369, "USP Silenced \"Black\"" },	
		{ 1370, "Assault Rifle \"Normal\"" },	
		{ 1371, "Assault Rifle \"Camouflage\"" },	
		{ 1372, "Assault Rifle \"Tiger Stripes\"" },	
		{ 1373, "Assault Rifle \"Black\"" },	
		{ 1374, "SPAS-12" },	
		{ 1375, "Automatic Shotgun \"Camouflage\"" },	
		{ 1376, "Automatic Shotgun \"Tiger Stripes\"" },	
		{ 1377, "Automatic Shotgun \"Black\"" },	
		{ 1382, "USP Silenced \"Tiger Stripes\"" },	
		{ 1383, "CT Helmet" },	
		{ 1385, "CT Face" },	
		{ 1387, "CT Gloves" },	
		{ 1388, "CT Boots" },	
		{ 1389, "CT Top Germany" },	
		{ 1390, "CT Top France" },	
		{ 1392, "CT Top Uk" },	
		{ 1393, "CT Top Usa" },	
		{ 1394, "CT Top Russia" },	
		{ 1395, "CT Bottom" },	
		{ 1396, "Terrorist Balaclava" },	
		{ 1397, "Terrorist Gloves" },	
		{ 1398, "Terrorist Boots" },	
		{ 1399, "Terrorist Vest" },	
		{ 1400, "Terrorist Pants Urban" },	
		{ 1401, "Terrorist Pants Jungle" },	
		{ 1402, "Terrorist Pants Artic" },	
		{ 1403, "Terrorist Pants Uni" },	
		{ 1416, "Terrorist Pants Tiger" },	
	};
}
