using System.IO;
using System.Reflection;
using System.Xml;
using UberStrike.Core.Types;
using UnityEditor;
using UnityEngine;

public static class CmuneClassGenerator
{
    public static readonly string Space = "    ";

    [MenuItem("Cmune Tools/Class Creator/Create GuiSkin BlueStonez.cs")]
    public static void CreateBlueStonezClass()
    {
        GUISkin skin = AssetDatabase.LoadAssetAtPath("Assets/Artwork/GUI/Resources/BlueStonez.GUISkin", typeof(GUISkin)) as GUISkin;
        CreateGuiSkinClass(skin, "BlueStonez");
    }

    [MenuItem("Cmune Tools/Class Creator/Create GuiSkin StormFront.cs")]
    public static void CreateStormFrontClass()
    {
        GUISkin skin = AssetDatabase.LoadAssetAtPath("Assets/Artwork/GUI/Resources/StormFront.GUISkin", typeof(GUISkin)) as GUISkin;
        CreateGuiSkinClass(skin, "StormFront");
    }

    public static void CreateGuiSkinClass(GUISkin skin, string name)
    {
        if (!skin)
        {
            Debug.LogError(name + " GUISkin not found!");
            return;
        }

        //CREATE CLASS
        StreamWriter writer = new StreamWriter("Assets/Scripts/GUI/Common/" + name + ".cs", false);

        writer.WriteLine("/////////////////////////////////////////////////");
        writer.WriteLine("/// This file was autogenerated by a Class Creator");
        writer.WriteLine("///");
        writer.WriteLine("/// WARNING! All changes in this file will be lost!");
        writer.WriteLine("/////////////////////////////////////////////////");
        writer.WriteLine();

        //usings
        writer.WriteLine("using UnityEngine;");
        writer.WriteLine();

        //class begin
        writer.WriteLine("public static class " + name);
        writer.WriteLine("{");

        //Function to Initialize the Values
        {
            writer.WriteLine(Space + "static " + name + "()");
            writer.WriteLine(Space + "{");
            writer.WriteLine(Space + Space + "Skin = Resources.Load(\"" + name + "\", typeof(GUISkin)) as GUISkin;");
            writer.WriteLine();

            //builtIin styles
            foreach (PropertyInfo i in typeof(GUISkin).GetProperties())
            {
                if (i.PropertyType == typeof(GUIStyle))
                    writer.WriteLine("{0}{0}{1} = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle(\"{1}\"));", Space, i.Name);
            }
            writer.WriteLine();
            //custom styles
            foreach (GUIStyle s in skin.customStyles)
            {
                writer.WriteLine("{0}{0}{1} = LocalizationHelper.GetLocalizedStyle(Skin.GetStyle(\"{1}\"));", Space, s.name);
            }
            writer.WriteLine(Space + "}");
            writer.WriteLine();
        }

        //Property
        writer.WriteLine(Space + "public static GUISkin Skin { get; private set; }");
        writer.WriteLine();

        //All Fields
        foreach (PropertyInfo i in typeof(GUISkin).GetProperties())
        {
            if (i.PropertyType == typeof(GUIStyle))
                writer.WriteLine(Space + "public static GUIStyle {0} {{ get; private set; }}", i.Name);
        }
        writer.WriteLine();
        foreach (GUIStyle s in skin.customStyles)
        {
            writer.WriteLine(Space + "public static GUIStyle {0} {{ get; private set; }}", s.name);
        }

        //class End
        writer.WriteLine("}");

        writer.Flush();
        writer.Close();

        Debug.Log(name + ".cs was updated");
    }
}
