/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////


public static class StringsHelp
{
    public static string ChatRules = @"1: No swearing or inappropriate content. Every time an inappropriate word is typed, three puppies and a kitten get caught in a revolving door.
2: No ""Caps lock"" (using it for emphasis is okay). Please only emphazise with discretion and tact.
3: No spamming. This includes baloney, rubbish, prattle, balderdash, hogwash, fatuity, drivel, mumbo jumbo, and canned precooked meat products.
4: Do not personally attack any person(s). If you happen to be a hata, don't be hatin, because the mods gonna be moderatin.
5: No backseat moderating. Believe it or not, we didn't add the convenient little 'Report Button' just because it looks pretty up there in the corner of the screen, although it does go nicely with that cute little gear symbol.
6: Do not discuss topics that involve race, color, creed, religion, sex, or politics. It's not like we play games to get extra exposure to the many issues we face constantly in our daily lives.";
}