/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class ConsumableHudTextures
{
    static ConsumableHudTextures()
    {
        var configurator = ((GameObject)Resources.Load("ConsumableHudTextures", typeof(GameObject))).GetComponent<Texture2DConfigurator>();
        TooltipDown = configurator.Textures[0];
        TooltipLeft = configurator.Textures[1];
        TooltipRight = configurator.Textures[2];
        TooltipUp = configurator.Textures[3];
        HealthBuffCharge = configurator.Textures[4];
        HealthBuffInstant = configurator.Textures[5];
        HealthBuffOvertime = configurator.Textures[6];
        AmmoBlue = configurator.Textures[7];
        AmmoRed = configurator.Textures[8];
        ArmorBlue = configurator.Textures[9];
        ArmorRed = configurator.Textures[10];
        HealthBlue = configurator.Textures[11];
        HealthRed = configurator.Textures[12];
        OffensiveGrenadeBlue = configurator.Textures[13];
        OffensiveGrenadeRed = configurator.Textures[14];
        SpringGrenadeBlue = configurator.Textures[15];
        SpringGrenadeRed = configurator.Textures[16];
        CircleBlue = configurator.Textures[17];
        CircleRed = configurator.Textures[18];
        CircleWhite = configurator.Textures[19];
    }

    public static Texture2D TooltipDown { get; private set; }
    public static Texture2D TooltipLeft { get; private set; }
    public static Texture2D TooltipRight { get; private set; }
    public static Texture2D TooltipUp { get; private set; }
    public static Texture2D HealthBuffCharge { get; private set; }
    public static Texture2D HealthBuffInstant { get; private set; }
    public static Texture2D HealthBuffOvertime { get; private set; }
    public static Texture2D AmmoBlue { get; private set; }
    public static Texture2D AmmoRed { get; private set; }
    public static Texture2D ArmorBlue { get; private set; }
    public static Texture2D ArmorRed { get; private set; }
    public static Texture2D HealthBlue { get; private set; }
    public static Texture2D HealthRed { get; private set; }
    public static Texture2D OffensiveGrenadeBlue { get; private set; }
    public static Texture2D OffensiveGrenadeRed { get; private set; }
    public static Texture2D SpringGrenadeBlue { get; private set; }
    public static Texture2D SpringGrenadeRed { get; private set; }
    public static Texture2D CircleBlue { get; private set; }
    public static Texture2D CircleRed { get; private set; }
    public static Texture2D CircleWhite { get; private set; }
}
