/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class HudTextures
{
    static HudTextures()
    {
        var configurator = ((GameObject)Resources.Load("HudTextures", typeof(GameObject))).GetComponent<Texture2DConfigurator>();
        AmmoBlue = configurator.Textures[0];
        AmmoRed = configurator.Textures[1];
        WhiteBlur128 = configurator.Textures[2];
        XPBarEmptyBlue = configurator.Textures[3];
        XPBarEmptyRed = configurator.Textures[4];
        XPBarFull = configurator.Textures[5];
        DeathScreenTab = configurator.Textures[6];
        DamageFeedbackMark = configurator.Textures[7];
        LevelUp = configurator.Textures[8];
        MGScale = configurator.Textures[9];
        MGTranslate = configurator.Textures[10];
        CNRotate = configurator.Textures[11];
        CNScale = configurator.Textures[12];
        HGTraslate = configurator.Textures[13];
        LRScale = configurator.Textures[14];
        LRTranslate = configurator.Textures[15];
        MWTranslate = configurator.Textures[16];
        SGScaleInside = configurator.Textures[17];
        SGScaleOutside = configurator.Textures[18];
        SPScale = configurator.Textures[19];
        SPTranslate = configurator.Textures[20];
        SRScale = configurator.Textures[21];
        SRTranslate = configurator.Textures[22];
        TargetCircle = configurator.Textures[23];
        ReticleSRZoom = configurator.Textures[24];
        QIBlue3 = configurator.Textures[25];
        QIBlue1 = configurator.Textures[26];
        QIRed3 = configurator.Textures[27];
        QIRed1 = configurator.Textures[28];
    }

    public static Texture2D AmmoBlue { get; private set; }
    public static Texture2D AmmoRed { get; private set; }
    public static Texture2D WhiteBlur128 { get; private set; }
    public static Texture2D XPBarEmptyBlue { get; private set; }
    public static Texture2D XPBarEmptyRed { get; private set; }
    public static Texture2D XPBarFull { get; private set; }
    public static Texture2D DeathScreenTab { get; private set; }
    public static Texture2D DamageFeedbackMark { get; private set; }
    public static Texture2D LevelUp { get; private set; }
    public static Texture2D MGScale { get; private set; }
    public static Texture2D MGTranslate { get; private set; }
    public static Texture2D CNRotate { get; private set; }
    public static Texture2D CNScale { get; private set; }
    public static Texture2D HGTraslate { get; private set; }
    public static Texture2D LRScale { get; private set; }
    public static Texture2D LRTranslate { get; private set; }
    public static Texture2D MWTranslate { get; private set; }
    public static Texture2D SGScaleInside { get; private set; }
    public static Texture2D SGScaleOutside { get; private set; }
    public static Texture2D SPScale { get; private set; }
    public static Texture2D SPTranslate { get; private set; }
    public static Texture2D SRScale { get; private set; }
    public static Texture2D SRTranslate { get; private set; }
    public static Texture2D TargetCircle { get; private set; }
    public static Texture2D ReticleSRZoom { get; private set; }
    public static Texture2D QIBlue3 { get; private set; }
    public static Texture2D QIBlue1 { get; private set; }
    public static Texture2D QIRed3 { get; private set; }
    public static Texture2D QIRed1 { get; private set; }
}
