/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;

public static class UberstrikeTextures
{
    static UberstrikeTextures()
    {
        var configurator = ((GameObject)Resources.Load("UberstrikeTextures", typeof(GameObject))).GetComponent<Texture2DConfigurator>();
        IconLottery = configurator.Textures[0];
        CreditsIcon32x32 = configurator.Textures[1];
        CreditsIcon48x48 = configurator.Textures[2];
        CreditsIcon75x75 = configurator.Textures[3];
        Points48x48 = configurator.Textures[4];
        IconCredits20x20 = configurator.Textures[5];
        IconPoints20x20 = configurator.Textures[6];
        Waiting = configurator.Textures[7];
        ItemSlotSelected = configurator.Textures[8];
    }

    public static Texture2D IconLottery { get; private set; }
    public static Texture2D CreditsIcon32x32 { get; private set; }
    public static Texture2D CreditsIcon48x48 { get; private set; }
    public static Texture2D CreditsIcon75x75 { get; private set; }
    public static Texture2D Points48x48 { get; private set; }
    public static Texture2D IconCredits20x20 { get; private set; }
    public static Texture2D IconPoints20x20 { get; private set; }
    public static Texture2D Waiting { get; private set; }
    public static Texture2D ItemSlotSelected { get; private set; }
}
