/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;
using System.Collections.Generic;

public static class GameAudio
{
    private static Dictionary<Clips, AudioClip> _allClips;

    static GameAudio()
    {
        var configurator = ((GameObject)Resources.Load("GameAudio", typeof(GameObject))).GetComponent<AudioConfigurator>();
        _allClips = new Dictionary<Clips, AudioClip>(configurator.Clips.Count);

        _allClips[Clips.AmmoPickup] = configurator.Clips[0];
        _allClips[Clips.WeaponPickup] = configurator.Clips[1];
        _allClips[Clips.BigHealth] = configurator.Clips[2];
        _allClips[Clips.MegaHealth] = configurator.Clips[3];
        _allClips[Clips.MediumHealth] = configurator.Clips[4];
        _allClips[Clips.SmallHealth] = configurator.Clips[5];
        _allClips[Clips.GoldArmor] = configurator.Clips[6];
        _allClips[Clips.SilverArmor] = configurator.Clips[7];
        _allClips[Clips.ArmorShard] = configurator.Clips[8];
        _allClips[Clips.MatchEndingCountdown1] = configurator.Clips[9];
        _allClips[Clips.MatchEndingCountdown2] = configurator.Clips[10];
        _allClips[Clips.MatchEndingCountdown3] = configurator.Clips[11];
        _allClips[Clips.MatchEndingCountdown4] = configurator.Clips[12];
        _allClips[Clips.MatchEndingCountdown5] = configurator.Clips[13];
        _allClips[Clips.LevelUp] = configurator.Clips[14];
        _allClips[Clips.FocusEnemy] = configurator.Clips[15];
        _allClips[Clips.GameOver] = configurator.Clips[16];
        _allClips[Clips.BlueWins] = configurator.Clips[17];
        _allClips[Clips.RedWins] = configurator.Clips[18];
        _allClips[Clips.YouWin] = configurator.Clips[19];
        _allClips[Clips.Draw] = configurator.Clips[20];
        _allClips[Clips.Fight] = configurator.Clips[21];
        _allClips[Clips.LostLead] = configurator.Clips[22];
        _allClips[Clips.TakenLead] = configurator.Clips[23];
        _allClips[Clips.TiedLead] = configurator.Clips[24];
        _allClips[Clips.MagicItem] = configurator.Clips[25];
        _allClips[Clips.CountdownTonal1] = configurator.Clips[26];
        _allClips[Clips.CountdownTonal2] = configurator.Clips[27];
        _allClips[Clips.MinorAlert] = configurator.Clips[28];
        _allClips[Clips.KlaxonAlarm] = configurator.Clips[29];
        _allClips[Clips.GetCredits] = configurator.Clips[30];
        _allClips[Clips.GetPoints] = configurator.Clips[31];
        _allClips[Clips.GetXP] = configurator.Clips[32];
    }

    public static AudioClip Get(Clips clip)
    {
        return _allClips[clip];
    }

    public enum Clips
    {
        AmmoPickup,
        WeaponPickup,
        BigHealth,
        MegaHealth,
        MediumHealth,
        SmallHealth,
        GoldArmor,
        SilverArmor,
        ArmorShard,
        MatchEndingCountdown1,
        MatchEndingCountdown2,
        MatchEndingCountdown3,
        MatchEndingCountdown4,
        MatchEndingCountdown5,
        LevelUp,
        FocusEnemy,
        GameOver,
        BlueWins,
        RedWins,
        YouWin,
        Draw,
        Fight,
        LostLead,
        TakenLead,
        TiedLead,
        MagicItem,
        CountdownTonal1,
        CountdownTonal2,
        MinorAlert,
        KlaxonAlarm,
        GetCredits,
        GetPoints,
        GetXP,
    }
}