/////////////////////////////////////////////////
/// This file was autogenerated by a Class Creator
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using UnityEngine;
using System.Collections.Generic;

public static class UIAudio
{
    private static Dictionary<Clips, AudioClip> _allClips;

    static UIAudio()
    {
        _allClips = new Dictionary<Clips, AudioClip>();
        var configurator = ((GameObject)Resources.Load("UIAudio", typeof(GameObject))).GetComponent<AudioConfigurator>();

        _allClips[Clips.AudioVolumn] = configurator.Clips[0];
        _allClips[Clips.ButtonClick] = configurator.Clips[1];
        _allClips[Clips.ButtonRollover] = configurator.Clips[2];
        _allClips[Clips.ClickReady] = configurator.Clips[3];
        _allClips[Clips.ClickUnready] = configurator.Clips[4];
        _allClips[Clips.CloseLoadout] = configurator.Clips[5];
        _allClips[Clips.ClosePanel] = configurator.Clips[6];
    }

    public static AudioClip Get(Clips clip)
    {
        return _allClips[clip];
    }

    public enum Clips
    {
        AudioVolumn,
        ButtonClick,
        ButtonRollover,
        ClickReady,
        ClickUnready,
        CloseLoadout,
        ClosePanel,
    }
}
